//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVDepartment
    {
        public CVDepartment()
        {
            this.Departments = new HashSet<Department>();
            this.Managers = new HashSet<Manager>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Manager> Managers { get; set; }
    }
}
