//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVPermission
    {
        public CVPermission()
        {
            this.Permissions = new HashSet<Permissions>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
