//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int EmpID { get; set; }
        public string Title1 { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual CVTitle CVTitle { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
